const escapeHtml = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const params = new URLSearchParams(location.search);
const main = document.querySelector('main');
const projectUrl = p => `index.html?project=${encodeURIComponent(p.id)}`;
const art = (p, i) => `<div class="art" role="img" aria-label="${escapeHtml(p.title)} — placeholder artwork"><span class="art-number">${String(i + 1).padStart(2, '0')}</span><span class="art-label">Image forthcoming</span></div>`;
const tags = p => p.tech.map(t => `<span class="tag">${escapeHtml(t)}</span>`).join('');
const bullets = items => `<ul>${items.map(t => `<li>${escapeHtml(t)}</li>`).join('')}</ul>`;
const card = (p, i) => `<a class="card" href="${projectUrl(p)}">${art(p, i)}<h3>${escapeHtml(p.title)} <span aria-hidden="true">↗</span></h3><p>${escapeHtml(p.company ? `${p.company} / ${p.category}` : p.category)}</p></a>`;
function listing(personal) {
    const projects = personal ? personalProjects : professionalProjects;
    document.title = `${personal ? 'Personal projects' : 'Professional projects'} — Thanos Restas`;
    main.innerHTML = `<section class="intro"><p class="eyebrow">${personal ? 'EXPERIMENTS & EXPLORATIONS' : 'THANOS RESTAS / SELECTED WORK'}</p><h1>${personal ? 'Made out of<br><em>curiosity.</em>' : 'Practical tools.<br><em>Immersive experiences.</em>'}</h1><p>${personal ? 'Games, prototypes, and creative coding. A collection of personal projects, including my university thesis.' : 'Software engineer building enterprise platforms, desktop tools, and experiences across augmented and virtual reality.'}</p></section><div class="section-heading"><h2>${personal ? 'Personal projects' : 'Professional projects'}</h2><span>${String(projects.length).padStart(2, '0')} PROJECTS</span></div><section class="grid" aria-label="${personal ? 'Personal' : 'Professional'} projects">${projects.map(card).join('')}</section><div class="resume-callout"><p>The experience behind the projects.</p><a class="button" href="index.html?page=resume">Explore my resume ↗</a></div>`;
}
function projectPage(id) {
    const all = [...professionalProjects, ...personalProjects], p = all.find(p => p.id === id);
    if (!p) { document.title = 'Project not found — Thanos Restas'; main.innerHTML = '<section class="intro"><h1>Project not found.</h1><a class="button" href="index.html">Return to professional projects</a></section>'; return; }
    document.title = `${p.title} — Thanos Restas`;
    const personal = !!p.repo;
    main.innerHTML = `<a class="back" href="index.html${personal ? '?page=personal' : ''}">← All ${personal ? 'personal' : 'professional'} projects</a><section class="project-header"><p class="eyebrow">${escapeHtml(p.category)}</p><h1>${escapeHtml(p.title)}</h1><p class="metadata">${escapeHtml(p.company ? `${p.company} · ${p.dates}` : 'Personal project')}</p></section><div class="detail-layout"><aside>${art(p, all.indexOf(p))}</aside><article class="prose"><h2>Overview</h2><p>${escapeHtml(p.overview)}</p>${p.contributions.length ? `<h2>${personal ? 'Project details' : 'My contributions'}</h2>${bullets(p.contributions)}` : ''}${p.tech.length ? `<h2>Technologies</h2><div>${tags(p)}</div>` : ''}${p.repo ? `<p><a class="button" href="https://github.com/ThanosRestas/${encodeURIComponent(p.repo)}">View source on GitHub ↗</a></p>` : ''}</article></div>`;
}
function resume() {
    document.title = 'Resume — Thanos Restas';
    main.innerHTML = `<section class="intro"><p class="eyebrow">EXPERIENCE & BACKGROUND</p><h1>Thanos Restas</h1><p>Software Engineer · Thessaloniki, Greece</p><a class="button" href="Thanos_Restas_CV.pdf" download>Download CV (PDF) ↓</a></section><article class="resume"><p class="summary">Software engineer working across enterprise platforms, desktop applications, development tools, XR, and games. I turn ideas into practical tools through quick prototyping, rapid iteration, and direct communication with colleagues.</p><section class="resume-section"><h2>Experience</h2><div class="job"><h3>Software Engineer · Chubb</h3><p class="metadata">April 2025 – Present · Thessaloniki, Greece</p><h4><a href="${projectUrl(professionalProjects[0])}">Ignite E-Trade & Underwriting Platform ↗</a></h4>${bullets(professionalProjects[0].contributions)}</div><div class="job"><h3>Software Engineer · CERTH</h3><p class="metadata">July 2020 – April 2025 · Thessaloniki, Greece</p><p>Centre for Research & Technology Hellas. Concurrent projects across desktop software, industrial tools, and immersive applications.</p>${professionalProjects.slice(1).map(p => `<section><h4><a href="${projectUrl(p)}">${escapeHtml(p.title)} ↗</a></h4><p class="metadata">${escapeHtml(p.dates)}</p><p>${escapeHtml(p.overview)}</p>${bullets(p.contributions)}</section>`).join('')}</div><div class="job"><h3>Software Engineer Intern · CERTH</h3><p class="metadata">July 2017 – August 2017 · Thessaloniki, Greece</p>${bullets(['Explored 2D WebGL development.', 'Implemented the Singleton design pattern to manage the state of scene objects.', 'Experimented with Unity and procedural mesh generation.'])}</div></section><section class="resume-section"><h2>Education</h2><h3>Ionian University</h3><p>BS, Informatics · Humanistic Informatics<br>Corfu, Greece</p><p>Thesis: <a href="index.html?project=theasis">Theasis — a first-person shooter for the web using BabylonJS ↗</a></p></section><section class="resume-section"><h2>Skills</h2><p><strong>Proficient:</strong> C#, Java, JavaScript<br><strong>Familiar:</strong> C++, Python</p><p>.NET, WPF, XAML, Unity, Mendix, PostgreSQL, SQL, Docker, Git, Visual Studio, Postman, Bash</p></section><section class="resume-section"><h2>Certifications</h2>${bullets(['Mendix Rapid Developer', 'Advanced Prompt Engineering Techniques', 'What Is Generative AI?', 'Generative AI for Business Leaders', 'Integrating Generative AI into the Creative Process'])}</section><section class="resume-section"><h2>Publication</h2><p>A Collaborative AR/VR Platform for Social Manufacturing</p></section></article>`;
}
if (params.has('project')) projectPage(params.get('project')); else if (params.get('page') === 'resume') resume(); else listing(params.get('page') === 'personal');
const active = params.get('page') === 'resume' ? 'index.html?page=resume' : params.get('page') === 'personal' || personalProjects.some(p => p.id === params.get('project')) ? 'index.html?page=personal' : 'index.html';
document.querySelectorAll('nav a').forEach(a => { if (a.getAttribute('href') === active) a.setAttribute('aria-current', 'page'); });
document.querySelector('#year').textContent = new Date().getFullYear();
