export type Project = {
  id: string;
  title: string;
  category: string;
  tech: string[];
  overview: string;
  contributions: string[];
  image?: string;
  imageAlt?: string;
  company?: string;
  dates?: string;
  repo?: string;
};

export const professionalProjects: Project[] = [
  { id: 'ignite', title: 'Ignite Underwriting Platform', company: 'Chubb', dates: 'April 2025 – Present', category: 'Enterprise software', tech: ['Java', 'JavaScript', 'PostgreSQL', 'Mendix'], image: 'project-images/underwriting-platform.png', imageAlt: 'Chubb wordmark on a navy background', overview: 'Full-stack development for Chubb’s Ignite E-Trade and Underwriting platform, translating business requirements into features for an enterprise insurance platform.', contributions: ['Deliver full-stack features and extend platform capabilities with custom Java actions, JavaScript, and PostgreSQL data modelling.', 'Own implementation, testing, and deployment through SIT and UAT environments.', 'Partner with Business Analysts to refine requirements into feasible implementation plans.', 'Participate in on-call rotation and releases, diagnose incidents, and deploy production hotfixes.', 'Collaborate with multiple teams on shared platform architecture and integrations.'] },
  { id: 'revit-assembly-design', title: 'Revit Assembly Design', company: 'CERTH', dates: 'March 2024 – April 2025', category: 'Desktop tools · CAD', tech: ['C#', '.NET', 'WPF', 'XAML', 'ASP.NET Core', 'MSSQL', 'Docker'], image: 'project-images/revit-assembly-design.png', imageAlt: 'Autodesk Revit logo on a white background', overview: 'An Autodesk Revit plugin for custom assembly design and management, combining a purpose-built drawing interface with a maintained backend.', contributions: ['Designed and developed WPF/XAML interface elements.', 'Created a custom 2D canvas for drawing and erasing rectangles and straight lines, with measuring and zoom controls.', 'Introduced a state machine to manage canvas interaction states.', 'Designed and integrated an undo/redo system using the Command Pattern.', 'Implemented a ruler to dynamically display the dimensions of drawn shapes.', 'Refactored the codebase for readability and maintainability.', 'Containerized and maintained the ASP.NET Core backend and MSSQL database with Docker.'] },
  { id: 'industrial-training', title: 'Industrial Training & Manuals', company: 'CERTH', dates: 'September 2022 – April 2025', category: 'Desktop application', tech: ['C#', '.NET', 'WPF', 'XAML', 'MVVM', 'Node.js', 'RestSharp', 'Git'], image: 'project-images/industrial-training.jpg', imageAlt: 'Black line drawing of a mechanical gear', overview: 'A Windows desktop application for creating device training materials and user manuals for industrial settings, developed within a complex legacy codebase.', contributions: ['Maintained and improved a complex, undocumented WPF application.', 'Implemented the MVVM architectural pattern for new features and updated XAML views and viewmodels.', 'Modified Node.js server code to serve files created by the application.', 'Designed and integrated a login screen and used RestSharp for authentication and REST API data transfers.', 'Identified and resolved local filesystem I/O and data management issues, and improved file handling procedures.', 'Set up version control using Git.'] },
  { id: 'volumetric-video', title: 'AR Volumetric Video Player', company: 'CERTH', dates: 'September 2021 – April 2025', category: 'Augmented reality · Mobile', tech: ['Unity', 'C#', 'Python', 'MeshLab', 'FFmpeg', 'Draco', 'KTX2'], image: 'project-images/dancewalk.jpg', imageAlt: 'Dancewalk volumetric video preview for the AR player project', overview: 'An augmented reality mobile application for volumetric video playback, with a preprocessing pipeline that converts point cloud content into textured mesh sequences.', contributions: ['Built a Python and MeshLab pipeline from PLY point clouds to OBJ and PNG, and to compressed glTF sequences.', 'Implemented Draco-compressed glTF sequence import and Unity mesh creation.', 'Combined glTF and KTX2 texture compression to reduce file size and memory consumption.', 'Built real-time MP4 frame-to-Texture2D extraction for mesh texturing.', 'Implemented the mobile interface and profiled the application to support low-end devices.', 'Handled Google Play Console internal testing and publishing.', 'Integrated Unity Localization to support application localization.'] },
  { id: 'iproduce', title: 'iProduce', company: 'CERTH', dates: 'January 2021 – April 2025', category: 'AR/VR · Product configurator', tech: ['Unity', 'C#', 'JavaScript', 'Mirror Networking', 'AR Foundation', 'ZXing.Net', 'HoloLens'], image: 'project-images/iproduce.png', imageAlt: 'iProduce wordmark and light bulb logo on a white background', overview: 'An AR/VR product configurator and collaboration tool delivered across WebGL, Android, and Microsoft HoloLens.', contributions: ['Owned and maintained WebGL, Android, and HoloLens versions of the application.', 'Implemented WebGL single sign-on using token-based authentication and C#–JavaScript browser interaction, and integrated REST APIs.', 'Prototyped ownership exchange between LAN clients manipulating a shared GameObject with Mirror Networking.', 'Automated material creation from textures with Unity Editor scripting.', 'Designed and developed interface interactions for the WebGL application.', 'Ported the application to Android, integrated AR Foundation, and added QR scanning with ZXing.Net for 3D model downloads.', 'Ported the application and adapted its interface for HoloLens mixed reality interaction.'] },
  { id: 'aribfa', title: 'ARIBFA', company: 'CERTH', dates: 'July 2020 – February 2022', category: 'Mixed reality · AEC', tech: ['Unity', 'C#', 'HoloLens', 'MRTK', 'JSON', 'REST'], image: 'project-images/aribfa.jpg', imageAlt: 'Mixed reality screenshot showing the ARIBFA component annotation interface', overview: 'A HoloLens application for architecture, engineering, and construction, supporting BIM/IFC data visualization and annotations of building components.', contributions: ['Designed a 3D MRTK menu system for real-time BIM/IFC data visualization and editing.', 'Implemented mixed reality text annotations of BIM MEP components.', 'Created JSON serialization for creating, editing, and saving annotation data.', 'Integrated RESTful services using UnityWebRequest for sharing in-building user locations and annotation data.'] },
  { id: 'activator', title: 'ActiVatoR', company: 'CERTH', dates: 'July 2020 – February 2021', category: 'Virtual reality · Education', tech: ['Unity', 'C#', 'HTC Vive', 'NavMesh', 'Timeline'], image: 'project-images/activator.jpg', imageAlt: 'ActiVatoR game screenshot showing a snowy village and volcano', overview: 'A serious virtual reality educational game with NPC behavior and a simulated volcanic eruption.', contributions: ['Implemented Navigation Mesh Agent actions with Unity coroutines to manage NPC patrol behavior.', 'Implemented ballistic projectile movement.', 'Used Unity Timeline events and triggers to simulate the sequence of a volcanic eruption.'] }
];
export const personalProjects: Project[] = [
  { id: 'theasis', title: 'Theasis', category: 'University thesis · Web game', tech: ['JavaScript', 'HTML', 'CSS', 'BabylonJS'], repo: 'Theasis', overview: 'A first-person shooter for the web, developed as my Informatics thesis at Ionian University.', contributions: ['Built a browser-based FPS using BabylonJS.', 'The game features five world sections, five animated weapons, and four enemy types.', 'Includes health and energy consumables, sprinting, ammunition pickups, a player HUD, and enemy health bars.'] },
  { id: 'sheep-game', title: 'Untitled Sheep Game', category: 'Virtual pet · Android prototype', tech: ['Unity', 'C#', 'Android'], repo: 'Untitled-Sheep-Game', overview: 'A virtual pet prototype for Android devices, created in Unity.', contributions: [] },
  { id: 'estia', title: 'Estia', category: 'Home design · Prototype', tech: [], repo: 'Estia', overview: 'A proof of concept for a home design toolkit and web application.', contributions: [] },
  { id: 'tic-tac-toe', title: 'Tic Tac Toe', category: 'Game development · SDL', tech: ['C', 'C++', 'SDL'], repo: 'TicTacToe-SDL', overview: 'A two-player hotseat implementation of Tic Tac Toe using SDL.', contributions: ['Explored the main game loop, image loading, and mouse input.'] },
  { id: 'pong', title: 'Pong', category: 'Game development · SDL', tech: ['SDL'], repo: 'Pong-SDL', overview: 'A recreation of Pong using SDL.', contributions: [] },
  { id: 'breakout', title: 'Breakout', category: 'Game development · SDL', tech: ['C', 'C++', 'SDL'], repo: 'Breakout-SDL', overview: 'A single-player recreation of Breakout using SDL.', contributions: ['Created levels using a tilemap and explored collision handling.', 'Implemented keyboard-controlled paddle movement.'] }
];
